### Base URL

@baseUrl = http://localhost:8080/spreadsheet

### Gameの作成

POST {{baseUrl}}/games
Content-Type: application/json

{ "games": 
    [
        {
            "modeId": "1",
            "modeDetailId": "1",
            "datetime": "2024-01-01T10:00:00",
            "myDeckId": "1",
            "isFirstAttack": "true",
            "opDeckId": "3",
            "result": "2",
            "remarks": "あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ"
        },
        {
            "modeId": "1",
            "modeDetailId": "1",
            "datetime": "2024-01-01T10:00:00",
            "myDeckId": "1",
            "isFirstAttack": "true",
            "opDeckId": "3",
            "result": "2",
            "remarks": "あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ"
        },
        {
            "modeId": "10",
            "modeDetailId": "1",
            "datetime": "2024-01-01T10:00:00",
            "myDeckId": "1",
            "isFirstAttack": "true",
            "opDeckId": "3",
            "result": "2",
            "remarks": "あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ"
        }
    ]
}